---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc2
  labels:
    app: nginx
spec:
  type: NodePort  # Change to NodePort
  ports:
  - port: 80
    nodePort: 30000  # Specify a NodePort (between 30000-32767)
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
