apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort  # Change to NodePort
  ports:
  - port: 80
    nodePort: 30000  # Specify a NodePort (between 30000-32767)
  selector:
    app: nginx
